# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Almel < Formula
  desc "Fast and customizable shell prompt"
  homepage "https://github.com/Ryooooooga/almel"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.0/almel-v1.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "1792297f08fd1153b2d6781ab8f027e55d3320a0896c297029b48180b3cb9cb8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.0/almel-v1.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "77e80cdc7c25c26e520032fde563b80334c46f727ac27324e13aac95880aeed7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.0/almel-v1.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "30c835de9ba91921fbf7b7d9c0125dd504d6c64408c115e5a87a503027ace3df"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.0/almel-v1.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cf2bfe73ba68e2d94d8ad532308aea9ec6b04954472987f020eca86a756627a0"
    end
  end

  def install
    bin.install "almel"
  end

  test do
    system "#{bin}/almel", "--version"
  end
end
