# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Almel < Formula
  desc "Fast and customizable shell prompt"
  homepage "https://github.com/Ryooooooga/almel"
  version "1.3.1+1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.3.1+1/almel-v1.3.1+1-x86_64-apple-darwin.tar.gz"
      sha256 "9ec63782d3cf78d9f5d927b2b33e5afa5f96209aeeca73fe055a50f383f2000d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.3.1+1/almel-v1.3.1+1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "687d9769e46ff36fb63b713d236f61b485bd8edd59981ebd5a13f9581eef6af8"
    end
  end

  def install
    bin.install "almel"
  end
end
