# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Almel < Formula
  desc "Fast and customizable shell prompt"
  homepage "https://github.com/Ryooooooga/almel"
  version "1.4.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.5/almel-v1.4.5-x86_64-apple-darwin.tar.gz"
      sha256 "2f624c745a4b701b28c49189cc21994ba580a2bb95da3c29a7827dae76209337"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.5/almel-v1.4.5-aarch64-apple-darwin.tar.gz"
      sha256 "fc7b2639b538df7761142080c3b206ce790b90933cec5bccb1ab9eceb1a5f184"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.5/almel-v1.4.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0e7d2f8d9fff029e9d8a0b1e64ab5e79e7a3415155077be53044351ceab00b42"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/almel/releases/download/v1.4.5/almel-v1.4.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "80f82d378b04a97147bc2e3b54ded9fcef54edc1fc73a8f8ddfe4bf6aaec6655"
    end
  end

  def install
    bin.install "almel"
  end

  test do
    system "#{bin}/almel", "--version"
  end
end
