# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Croque < Formula
  desc "Fast and customizable shell prompt"
  homepage "https://github.com/Ryooooooga/croque"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/croque/releases/download/v0.1.1/croque-v0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "2b986f4088a4aef061576785c9ac73475b140f3bd9b66969ac9f83e1002398b0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/croque/releases/download/v0.1.1/croque-v0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "7d5c1ef7c8abdb4bcf4ca32e13212ee890e4a46594c8da8cef24fdb4660b9cb1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/croque/releases/download/v0.1.1/croque-v0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "715a655ebc9f165ec5bcf8c5470dc063098b2ab3a69bc10a1fbf1577cd8f0154"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/croque/releases/download/v0.1.1/croque-v0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "88ba24f56956425486af87cc4c46c29e1406dd9e3439bc77ab6954b960cd47aa"
    end
  end

  def install
    bin.install "croque"
  end

  test do
    system "#{bin}/croque", "--version"
  end
end
