# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qwy < Formula
  desc "Zsh Fuzzy Completion Plugin"
  homepage "https://github.com/Ryooooooga/qwy"
  version "0.1.0-preview+8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/qwy/releases/download/v0.1.0-preview+8/qwy_0.1.0-preview+8_darwin_arm64.tar.gz"
      sha256 "3bba61e44240b66a1e4209f80b4bf68ea799b6e79d0867658ba945189e9d1e09"

      def install
        bin.install "qwy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/qwy/releases/download/v0.1.0-preview+8/qwy_0.1.0-preview+8_darwin_amd64.tar.gz"
      sha256 "803cba5886851c3fdf993f6b533b95d0a0c640a00ac953ada7868e8f0598a15d"

      def install
        bin.install "qwy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/qwy/releases/download/v0.1.0-preview+8/qwy_0.1.0-preview+8_linux_arm64.tar.gz"
      sha256 "7f73bd6e98bb70104036f6f575aab34dafc01f8ccae64cd9c5a1367384f18d48"

      def install
        bin.install "qwy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/qwy/releases/download/v0.1.0-preview+8/qwy_0.1.0-preview+8_linux_amd64.tar.gz"
      sha256 "2d723c64f90a471941bf8e512817ce9f3a8eaf223d9bb5dad9422c404ea2f854"

      def install
        bin.install "qwy"
      end
    end
  end

  test do
    system "#{bin}/qwy", "--version"
  end
end
