# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Zabrze < Formula
  desc "ZSH abbreviation expansion plugin"
  homepage "https://github.com/Ryooooooga/zabrze"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.1.9/zabrze-v0.1.9-x86_64-apple-darwin.tar.gz"
      sha256 "878bcc8034df1225b56dd7cca5a7e8c826102bffa0aa06f20ad7bfeebe8c3025"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.1.9/zabrze-v0.1.9-aarch64-apple-darwin.tar.gz"
      sha256 "2cbc0088261811b5cc390bbc2eeed750a35313ea9e6b25408b4ccde9f49ad3b6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.1.9/zabrze-v0.1.9-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d7dbd56f2921a3269ddaabd0b5fbdc390792b02809b43086a68189959fc91b9e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.1.9/zabrze-v0.1.9-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "42a82e43a96d3367170369c4cc06159b713b48404f8ab13e952d2a551cdd2839"
    end
  end

  def install
    bin.install "zabrze"
  end

  test do
    system "#{bin}/zabrze", "--version"
  end
end
