# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Zabrze < Formula
  desc "ZSH abbreviation expansion plugin"
  homepage "https://github.com/Ryooooooga/zabrze"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.4.1/zabrze-v0.4.1-x86_64-apple-darwin.tar.gz"
      sha256 "e8eed4cb538fbdec4d2a3931a3295f4361b5e010a0e70bf5c28e6498ad40a06f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.4.1/zabrze-v0.4.1-aarch64-apple-darwin.tar.gz"
      sha256 "2af11a05c8194681f7db4b8380f91ffbc255089d364419bbe3aac4030f1e20e0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.4.1/zabrze-v0.4.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f97adab0c36c52cf73149b27a102df7ab89f799b3cdbde02497c8dac4c77a50f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/zabrze/releases/download/v0.4.1/zabrze-v0.4.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ddec61644edb0c9471720126c90a8de767e85c4efbbfbc97daad5e29e52e2420"
    end
  end

  def install
    bin.install "zabrze"
  end

  test do
    system "#{bin}/zabrze", "--version"
  end
end
