# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zouch < Formula
  desc "Create a new file from a template."
  homepage "https://github.com/Ryooooooga/zouch"
  version "0.3.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.8/zouch_0.3.8_darwin_amd64.tar.gz"
      sha256 "973d8c21cb104ec05525230762644a52b90ecd96fbe2b7f6f2fc7155ef1217d2"

      def install
        bin.install "zouch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.8/zouch_0.3.8_darwin_arm64.tar.gz"
      sha256 "ae99d87065cdb5a65f6968687235f774f93ac3bd7c4975346b0e611699babf7b"

      def install
        bin.install "zouch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.8/zouch_0.3.8_linux_arm64.tar.gz"
      sha256 "863fb2acaad3dfb08b8ff8a27d74c9284add2611878c734b6faa2b24967c93d9"

      def install
        bin.install "zouch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.8/zouch_0.3.8_linux_amd64.tar.gz"
      sha256 "36260fc6c76a97df7cb4f60fc9d5fc0fba27a00cfeb676f64effe8905de28b3f"

      def install
        bin.install "zouch"
      end
    end
  end

  test do
    system "#{bin}/zouch", "--version"
  end
end
