# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zouch < Formula
  desc "Create a new file from a template."
  homepage "https://github.com/Ryooooooga/zouch"
  version "0.3.6+2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.6+2/zouch_0.3.6+2_darwin_amd64.tar.gz"
      sha256 "ee0e94ca2b352b1c72ede2ee5913a000bf5ae14a6cf72daf6e0b7ccd094d4dd8"

      def install
        bin.install "zouch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.6+2/zouch_0.3.6+2_darwin_arm64.tar.gz"
      sha256 "8732a60f60935e28959267f8fd503ff37067c4b660895a59d9c07fa73e29ad03"

      def install
        bin.install "zouch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.6+2/zouch_0.3.6+2_linux_arm64.tar.gz"
      sha256 "53dfbc60189c24fd56bd61a6231483f3ed1f41010bd540349e007c6c307ede19"

      def install
        bin.install "zouch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ryooooooga/zouch/releases/download/v0.3.6+2/zouch_0.3.6+2_linux_amd64.tar.gz"
      sha256 "cd658d39f49d3753ca464fb53fa761d62f52d80a3daaa3ef43c0bc684661eb07"

      def install
        bin.install "zouch"
      end
    end
  end

  test do
    system "#{bin}/zouch", "--version"
  end
end
