name: CI

on:
  push:
    branches: [main]

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        target:
          - almel
          - zabrze
          - zouch
          - qwy
        os:
          - macOS-latest
          - ubuntu-latest

    name: Install - ${{ matrix.target }}:${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - run: brew install -v ryooooooga/tap/${{ matrix.target }}
      - run: brew test -v ${{ matrix.target }}
      - run: which ${{ matrix.target }}
