name: CI

on:
  push:
    branches: [main]

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        target:
          - almel
          - zabrze
          - zouch
        os:
          - macOS-latest
          - ubuntu-latest

    name: Install - ${{ matrix.target }}:${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: brew install ryooooooga/tap/${{ matrix.target }}
        run: brew install ryooooooga/tap/${{ matrix.target }}

      - name: ${{ matrix.target }} --version
        run: ${{ matrix.target }} --version
